# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3K9XokRzsEI3-aPxBwEufD4PVsQ9xfT

# #Wheather  modelling using the Quadratic Equation
"""

a = 5
b = 4
c = 6
x = 4.5
y = a*x*x+b*x+c
print('The value of y is ' ,y)