# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17e7MffML1c7oyZMh4C6Mexh2B0gsWILx
"""

with open('/content/data.txt', 'r') as file:
    a = float(file.readline())
    b = float(file.readline())
    c = float(file.readline())
    x = float(file.readline())
y = a * x * x + b * x + c
print('The value of y is:',y)